name = "DecomposingPolynomialSystems"
uuid = "f22b1612-9f73-4f98-889e-ed5396e1a4da"
authors = ["Viktor Korotynskiy <korotynskiy.viktor@gmail.com> and contributors"]
version = "1.0.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
AbstractAlgebra = "0.33-0.44"
Combinatorics = "1.0"
GAP = "0.10-0.13"
HomotopyContinuation = "2.9-2.13"
UnPack = "1.0"
julia = "1.10"

